"""
Streamlit demo for the AI-Powered Agentic Workflow for Project Management.

Two views:
1. "Run the Workflow" - runs the full pipeline (ActionPlanningAgent ->
   RoutingAgent -> KnowledgeAugmentedPromptAgent -> EvaluationAgent) on
   the Email Router product spec (or a spec you paste in) and shows
   every agent's real decision, including whether it came from the LLM
   or a fallback.
2. "Agent Playground" - run any of the seven agent classes individually
   with your own input, to explore the library outside the pilot
   workflow.
"""

from __future__ import annotations

import json
import os

import streamlit as st

# Bridge Streamlit secrets -> env var *before* any LLMService/LLMConfig
# is constructed, since workflow_agents/config.py resolves its provider
# from os.environ. Falls back silently to whatever's already in the
# environment (or nothing, i.e. offline mode) outside Streamlit Cloud.
try:
    if "GROQ_API_KEY" in st.secrets and not os.environ.get("GROQ_API_KEY"):
        os.environ["GROQ_API_KEY"] = st.secrets["GROQ_API_KEY"]
except Exception:
    pass

from agentic_workflow import load_product_spec, run_agentic_workflow
from workflow_agents.base_agents import (
    ActionPlanningAgent,
    AugmentedPromptAgent,
    DirectPromptAgent,
    EvaluationAgent,
    KnowledgeAugmentedPromptAgent,
    RAGKnowledgePromptAgent,
    RoutingAgent,
)
from workflow_agents.llm_service import LLMService

st.set_page_config(page_title="Agentic Workflow for Project Management", layout="wide")
st.title("AI-Powered Agentic Workflow for Project Management")
st.caption(
    "A planning agent breaks a goal into sub-tasks, a routing agent assigns each to a specialist "
    "team, knowledge-augmented agents generate the artifact, and evaluation agents score it - "
    "with every routing and planning decision genuinely made by the LLM, not hardcoded."
)

_probe_llm = LLMService()
live_mode = not _probe_llm.offline_mode
if live_mode:
    st.success(f"**Live LLM mode** - running on `{_probe_llm.config.model}` via `{_probe_llm.config.base_url}`.")
else:
    st.info(
        "**Offline mode** - no API key configured, so this runs on deterministic mock responses "
        "(free, no external calls). Add `GROQ_API_KEY` in Settings -> Secrets to switch to live mode."
    )

TEAM_LABELS = {
    "product_manager_team": "Product Manager team",
    "program_manager_team": "Program Manager team",
    "development_engineer_team": "Development Engineer team",
}

tab_workflow, tab_playground = st.tabs(["Run the Workflow", "Agent Playground"])

with tab_workflow:
    st.subheader("1. Product specification")
    default_spec = load_product_spec()
    product_spec = st.text_area("Edit the spec below, or run it as-is:", value=default_spec, height=220)

    if st.button("Run the agentic workflow", type="primary"):
        with st.spinner("Planning -> routing -> generating -> evaluating..."):
            result = run_agentic_workflow(offline_mode=not live_mode, product_spec=product_spec, write_output=False)
        st.session_state["workflow_result"] = result

    result = st.session_state.get("workflow_result")
    if result:
        st.subheader("2. Action plan")
        st.caption(
            "Generated by ActionPlanningAgent from the LLM's own breakdown of the goal - the number "
            "and content of sub-tasks can vary with the spec, it isn't a fixed list."
        )
        st.table(result["action_plan"])

        st.subheader("3. Work products, routing, and evaluation")
        for key, label in [
            ("user_stories", "User Stories"),
            ("product_features", "Product Features"),
            ("engineering_tasks", "Engineering Tasks"),
        ]:
            wp = result["work_products"].get(key)
            if not wp:
                continue
            evaluation = result["evaluation_summary"].get(key, {})
            with st.expander(f"{label}  ->  routed to {TEAM_LABELS.get(wp['assigned_route'], wp['assigned_route'])}", expanded=True):
                st.markdown("**Artifact:**")
                st.code(wp["artifact"], language=None)
                score = evaluation.get("score")
                passed = evaluation.get("passed")
                feedback = evaluation.get("feedback", "")
                badge = "✅ Passed" if passed else "⚠️ Needs work"
                st.markdown(f"**Evaluation:** {badge} · score {score}/10  \n{feedback}")

        with st.expander("Raw workflow JSON"):
            st.json(result)
        st.download_button(
            "Download project plan (JSON)",
            data=json.dumps(result, indent=2),
            file_name="email_router_project_plan.json",
            mime="application/json",
        )
    else:
        st.info("Click **Run the agentic workflow** above to generate a project plan.")

with tab_playground:
    st.subheader("Try any of the seven agent classes individually")
    agent_choice = st.selectbox(
        "Agent",
        [
            "DirectPromptAgent",
            "AugmentedPromptAgent",
            "KnowledgeAugmentedPromptAgent",
            "RAGKnowledgePromptAgent",
            "EvaluationAgent",
            "RoutingAgent",
            "ActionPlanningAgent",
        ],
    )

    llm = LLMService(offline_mode=not live_mode)
    user_input = st.text_area("Input", value="Explain technical project management in two sentences.", height=100)

    extra_output = None
    if agent_choice == "AugmentedPromptAgent":
        instruction = st.text_input("Persona/instruction", value="Answer as a technical project manager.")
        agent = AugmentedPromptAgent("AugmentedPromptAgent", instruction, llm)
    elif agent_choice == "KnowledgeAugmentedPromptAgent":
        knowledge = st.text_area("Knowledge base", value=load_product_spec(), height=120)
        instruction = st.text_input("Task instruction", value="Generate Agile user stories.")
        agent = KnowledgeAugmentedPromptAgent("KnowledgeAugmentedPromptAgent", knowledge, instruction, llm)
    elif agent_choice == "RAGKnowledgePromptAgent":
        docs_text = st.text_area(
            "Corpus (one document per line)",
            value="Email Router supports configurable routing rules.\nSLA dashboards report breaches in real time.\nAudit logs record every routing decision.",
            height=100,
        )
        agent = RAGKnowledgePromptAgent("RAGKnowledgePromptAgent", [d for d in docs_text.splitlines() if d.strip()], llm)
    elif agent_choice == "EvaluationAgent":
        criteria_text = st.text_input("Criteria (comma-separated)", value="clear, testable, actionable")
        agent = EvaluationAgent("EvaluationAgent", [c.strip() for c in criteria_text.split(",") if c.strip()], llm)
    elif agent_choice == "RoutingAgent":
        routes = {
            "product_manager_team": "Creates user stories and acceptance criteria.",
            "program_manager_team": "Defines features, milestones, dependencies, and risks.",
            "development_engineer_team": "Creates detailed engineering implementation tasks.",
        }
        agent = RoutingAgent("RoutingAgent", routes, llm)
    elif agent_choice == "ActionPlanningAgent":
        agent = ActionPlanningAgent("ActionPlanningAgent", llm)
    else:
        agent = DirectPromptAgent("DirectPromptAgent", llm)

    if st.button("Run agent"):
        with st.spinner(f"Running {agent_choice}..."):
            result = agent.run(user_input)
        st.markdown("**Output:**")
        if isinstance(result.output, (dict, list)):
            st.json(result.output)
        else:
            st.code(str(result.output), language=None)
        st.markdown("**Metadata:**")
        st.json(result.metadata)
