"""
Streamlit demo for the AI-Powered Agentic Workflow for Project Management.

Two views:
1. "Run the Workflow" - runs the full pipeline (ActionPlanningAgent ->
   RoutingAgent -> KnowledgeAugmentedPromptAgent -> EvaluationAgent) on
   the Email Router product spec (or a spec you paste in) and shows
   every agent's real decision, including whether it came from the LLM
   or a fallback.
2. "Agent Playground" - run any of the seven agent classes individually
   with your own input, to explore the library outside the pilot
   workflow.
"""

from __future__ import annotations

import json
import os

import streamlit as st

# Bridge Streamlit secrets -> env var *before* any LLMService/LLMConfig
# is constructed, since workflow_agents/config.py resolves its provider
# from os.environ. Falls back silently to whatever's already in the
# environment (or nothing, i.e. offline mode) outside Streamlit Cloud.
try:
    if "GROQ_API_KEY" in st.secrets and not os.environ.get("GROQ_API_KEY"):
        os.environ["GROQ_API_KEY"] = st.secrets["GROQ_API_KEY"]
except Exception:
    pass

from agentic_workflow import build_workflow, load_product_spec, run_agentic_workflow
from workflow_agents.base_agents import (
    ActionPlanningAgent,
    AugmentedPromptAgent,
    DirectPromptAgent,
    EvaluationAgent,
    KnowledgeAugmentedPromptAgent,
    RAGKnowledgePromptAgent,
    RoutingAgent,
)
from workflow_agents.llm_service import LLMService

st.set_page_config(page_title="Agentic Workflow for Project Management", layout="wide")
st.title("AI-Powered Agentic Workflow for Project Management")
st.caption(
    "A planning agent breaks a goal into sub-tasks, a routing agent assigns each to a specialist "
    "team, knowledge-augmented agents generate the artifact, and evaluation agents score it - "
    "with every routing and planning decision genuinely made by the LLM, not hardcoded."
)

_probe_llm = LLMService()
live_mode = not _probe_llm.offline_mode
if live_mode:
    st.success(f"**Live LLM mode** - running on `{_probe_llm.config.model}` via `{_probe_llm.config.base_url}`.")
else:
    st.info(
        "**Offline mode** - no API key configured, so this runs on deterministic mock responses "
        "(free, no external calls). Add `GROQ_API_KEY` in Settings -> Secrets to switch to live mode."
    )

TEAM_LABELS = {
    "product_manager_team": "Product Manager team",
    "program_manager_team": "Program Manager team",
    "development_engineer_team": "Development Engineer team",
}

# Which agent (from build_workflow()'s dict) and which final work_products
# key each route maps to, for both the auto-run and the manual stepper.
TEAM_TO_KEY = {
    "product_manager_team": ("user_stories", "pm", "story_eval"),
    "program_manager_team": ("product_features", "pgm", "feature_eval"),
    "development_engineer_team": ("engineering_tasks", "eng", "task_eval"),
}

HIGH_LEVEL_PROMPT = (
    "Transform the Email Router product specification into a structured technical project plan "
    "containing user stories, product features, and detailed engineering tasks."
)


def _render_workflow_result(result: dict) -> None:
    st.subheader("Action plan")
    st.caption(
        "Generated by ActionPlanningAgent from the LLM's own breakdown of the goal - the number "
        "and content of sub-tasks can vary with the spec, it isn't a fixed list."
    )
    st.table(result["action_plan"])

    st.subheader("Work products, routing, and evaluation")
    for key, label in [
        ("user_stories", "User Stories"),
        ("product_features", "Product Features"),
        ("engineering_tasks", "Engineering Tasks"),
    ]:
        wp = result["work_products"].get(key)
        if not wp:
            continue
        evaluation = result["evaluation_summary"].get(key, {})
        with st.expander(f"{label}  ->  routed to {TEAM_LABELS.get(wp['assigned_route'], wp['assigned_route'])}", expanded=True):
            st.markdown("**Artifact:**")
            st.code(wp["artifact"], language=None)
            score = evaluation.get("score")
            passed = evaluation.get("passed")
            feedback = evaluation.get("feedback", "")
            badge = "✅ Passed" if passed else "⚠️ Needs work"
            st.markdown(f"**Evaluation:** {badge} · score {score}/10  \n{feedback}")

    with st.expander("Raw workflow JSON"):
        st.json(result)
    st.download_button(
        "Download project plan (JSON)",
        data=json.dumps(result, indent=2),
        file_name="email_router_project_plan.json",
        mime="application/json",
    )


def _new_manual_state() -> dict:
    return {"agents": None, "plan": None, "step_idx": 0, "task_scratch": {}, "work_products": {}, "evaluation_summary": {}}


def _render_manual_stepper(product_spec: str) -> None:
    """Runs the exact same 10 LLM calls as the auto mode, but one button
    click per call - so a rate-limited free tier can be paced manually
    instead of firing all ~10 requests back to back.
    """
    ms = st.session_state.setdefault("manual_state", _new_manual_state())

    if st.button("Reset manual run"):
        st.session_state["manual_state"] = _new_manual_state()
        st.session_state.pop("workflow_result", None)
        st.rerun()

    if ms["agents"] is None:
        ms["agents"] = build_workflow(offline_mode=not live_mode, product_spec=product_spec)
    agents = ms["agents"]

    # --- Step 1: the planning call ---
    if ms["plan"] is None:
        st.markdown("**Next step: generate the action plan** (call 1 - `ActionPlanningAgent`)")
        if st.button("Run this step ▶", key="manual_step_plan"):
            with st.spinner("Calling ActionPlanningAgent..."):
                plan_result = agents["planner"].run(HIGH_LEVEL_PROMPT)
            ms["plan"] = plan_result.output
            st.rerun()
        return

    plan = ms["plan"]
    st.success(f"Action plan generated ({len(plan)} tasks).")
    st.table(plan)

    total_calls = 1 + 3 * len(plan)
    calls_done = 1 + ms["step_idx"]

    # --- Steps 2..N: route / generate / evaluate for each task, in order ---
    if ms["step_idx"] >= 3 * len(plan):
        st.success("All steps complete - results below.")
        st.session_state["workflow_result"] = {
            "project": "Email Router",
            "workflow_goal": HIGH_LEVEL_PROMPT,
            "action_plan": plan,
            "work_products": ms["work_products"],
            "evaluation_summary": ms["evaluation_summary"],
        }
        return

    task_idx, sub_step = divmod(ms["step_idx"], 3)
    task = plan[task_idx]
    task_key = task.get("id", f"T{task_idx + 1}")
    sub_labels = ["Route", "Generate artifact", "Evaluate artifact"]
    agent_names = ["RoutingAgent", "the assigned team's KnowledgeAugmentedPromptAgent", "the matching EvaluationAgent"]

    st.markdown(
        f"**Next step ({calls_done + 1} of {total_calls}): {sub_labels[sub_step]} for task `{task_key}` "
        f"- \"{task['objective']}\"** (call {calls_done + 1} - {agent_names[sub_step]})"
    )

    if st.button("Run this step ▶", key=f"manual_step_{ms['step_idx']}"):
        scratch = ms["task_scratch"].setdefault(task_key, {})
        with st.spinner(f"Calling {agent_names[sub_step]}..."):
            if sub_step == 0:
                routing_result = agents["router"].run(task["objective"])
                scratch["route"] = routing_result.output["route"]
                scratch["reason"] = routing_result.output.get("reason", "")
                scratch["fallback_used"] = routing_result.metadata.get("fallback_used", False)
            elif sub_step == 1:
                key, agent_key, _ = TEAM_TO_KEY[scratch["route"]]
                artifact_result = agents[agent_key].run(task["objective"])
                scratch["artifact"] = artifact_result.output
            else:
                key, _, eval_key = TEAM_TO_KEY[scratch["route"]]
                eval_result = agents[eval_key].run(scratch["artifact"])
                scratch["evaluation"] = eval_result.output
                ms["work_products"][key] = {"assigned_route": scratch["route"], "artifact": scratch["artifact"]}
                ms["evaluation_summary"][key] = scratch["evaluation"]
        ms["step_idx"] += 1
        st.rerun()

    # Show what's been completed so far, task by task.
    completed = [(k, v) for k, v in ms["task_scratch"].items() if v]
    if completed:
        st.divider()
        st.caption("Completed so far:")
        for k, v in completed:
            bits = []
            if "route" in v:
                fallback = " (keyword fallback)" if v.get("fallback_used") else ""
                bits.append(f"routed to **{TEAM_LABELS.get(v['route'], v['route'])}**{fallback}")
            if "artifact" in v:
                bits.append("artifact generated")
            if "evaluation" in v:
                bits.append(f"evaluated (score {v['evaluation'].get('score')}/10)")
            st.markdown(f"- `{k}`: " + ", ".join(bits))


tab_workflow, tab_playground = st.tabs(["Run the Workflow", "Agent Playground"])

with tab_workflow:
    st.subheader("1. Product specification")
    default_spec = load_product_spec()
    product_spec = st.text_area("Edit the spec below, or run it as-is:", value=default_spec, height=220)

    st.subheader("2. Run it")
    st.caption(
        "The full run makes ~10 sequential LLM calls (1 plan + 3 tasks x [route, generate, evaluate]). "
        "On a rate-limited free tier, step-by-step mode lets you pace those calls yourself."
    )
    mode = st.radio("Mode", ["Run everything at once", "Step through manually (one LLM call per click)"], horizontal=True)

    if mode == "Run everything at once":
        if st.button("Run the agentic workflow", type="primary"):
            with st.spinner("Planning -> routing -> generating -> evaluating..."):
                result = run_agentic_workflow(offline_mode=not live_mode, product_spec=product_spec, write_output=False)
            st.session_state["workflow_result"] = result
    else:
        _render_manual_stepper(product_spec)

    result = st.session_state.get("workflow_result")
    if result:
        st.subheader("3. Results")
        _render_workflow_result(result)
    elif mode == "Run everything at once":
        st.info("Click **Run the agentic workflow** above to generate a project plan.")

with tab_playground:
    st.subheader("Try any of the seven agent classes individually")
    agent_choice = st.selectbox(
        "Agent",
        [
            "DirectPromptAgent",
            "AugmentedPromptAgent",
            "KnowledgeAugmentedPromptAgent",
            "RAGKnowledgePromptAgent",
            "EvaluationAgent",
            "RoutingAgent",
            "ActionPlanningAgent",
        ],
    )

    llm = LLMService(offline_mode=not live_mode)
    user_input = st.text_area("Input", value="Explain technical project management in two sentences.", height=100)

    extra_output = None
    if agent_choice == "AugmentedPromptAgent":
        instruction = st.text_input("Persona/instruction", value="Answer as a technical project manager.")
        agent = AugmentedPromptAgent("AugmentedPromptAgent", instruction, llm)
    elif agent_choice == "KnowledgeAugmentedPromptAgent":
        knowledge = st.text_area("Knowledge base", value=load_product_spec(), height=120)
        instruction = st.text_input("Task instruction", value="Generate Agile user stories.")
        agent = KnowledgeAugmentedPromptAgent("KnowledgeAugmentedPromptAgent", knowledge, instruction, llm)
    elif agent_choice == "RAGKnowledgePromptAgent":
        docs_text = st.text_area(
            "Corpus (one document per line)",
            value="Email Router supports configurable routing rules.\nSLA dashboards report breaches in real time.\nAudit logs record every routing decision.",
            height=100,
        )
        agent = RAGKnowledgePromptAgent("RAGKnowledgePromptAgent", [d for d in docs_text.splitlines() if d.strip()], llm)
    elif agent_choice == "EvaluationAgent":
        criteria_text = st.text_input("Criteria (comma-separated)", value="clear, testable, actionable")
        agent = EvaluationAgent("EvaluationAgent", [c.strip() for c in criteria_text.split(",") if c.strip()], llm)
    elif agent_choice == "RoutingAgent":
        routes = {
            "product_manager_team": "Creates user stories and acceptance criteria.",
            "program_manager_team": "Defines features, milestones, dependencies, and risks.",
            "development_engineer_team": "Creates detailed engineering implementation tasks.",
        }
        agent = RoutingAgent("RoutingAgent", routes, llm)
    elif agent_choice == "ActionPlanningAgent":
        agent = ActionPlanningAgent("ActionPlanningAgent", llm)
    else:
        agent = DirectPromptAgent("DirectPromptAgent", llm)

    if st.button("Run agent"):
        with st.spinner(f"Running {agent_choice}..."):
            result = agent.run(user_input)
        st.markdown("**Output:**")
        if isinstance(result.output, (dict, list)):
            st.json(result.output)
        else:
            st.code(str(result.output), language=None)
        st.markdown("**Metadata:**")
        st.json(result.metadata)
